fix: remove unsupported orderBy arg from Discussion.comments GraphQL query
GitHub GraphQL API does not support 'orderBy' argument on the 'comments'
field of Discussion type. Removing it fixes:
  RuntimeError: GitHub GraphQL errors: Field 'comments' doesn't accept argument 'orderBy'

Both the initial query and pagination query in fetch_discussion() were affected.